name: ROS 2 Jazzy CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: auto_handeye_calibration
          target-ros2-distro: jazzy
          vcs-repo-file-url: ${{ github.workspace }}/dependencies.repos
